version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: melodia-postgres
    environment:
      POSTGRES_DB: melodiadb
      POSTGRES_USER: melodia_admin
      POSTGRES_PASSWORD: melodia_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U melodia_admin -d melodiadb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Melodía API
  melodia-api:
    build: .
    container_name: melodia-api
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: melodia_admin
      DATABASE_PASSWORD: melodia_password
      DATABASE_NAME: melodiadb
      HOST: 0.0.0.0
      PORT: 8080
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:

